BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "guild" (
	"guildID" TEXT NOT NULL UNIQUE,
	"adminRole" INTEGER DEFAULT NULL,
);

CREATE TABLE IF NOT EXISTS "config" (
	"key" TEXT NOT NULL UNIQUE,
	"value" TEXT NOT NULL
);

COMMIT;